# Site
name: 'darleigh.blog'
description: 'I genuinely want to use technology in my life to increase efficiency and provide long-term benefit for society.'
logo: 'https://darleigh.com/darleigh-logo_tran-2401-2236.png'
favicon: 'https://darleigh.com/assets/images/apple-icon.png'
baseurl: '/'
disqus: 'Valuable insights on knowledge, experience, and adventures.'
email: 'duongnguyen.22@icloud.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Duong Nguyen
      site:           https://darleigh.com
      avatar:         https://github.com/darleigh/site/blob/main/assets/images/avatar/darleigh.jpg?raw=true
      bio:            "Hello"
      email:          duongnguyen.22@icloud.com
      # facebook:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]